apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: koo-api
  template:
    metadata:
      labels:
        deployment: koo-api
    spec:
      containers:
      - name: the-container
        image: koogg/koo-api:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 300
          periodSeconds: 15
        readinessProbe:
          httpGet:
          path: /
          port: 9080
        initialDelaySeconds: 45
        periodSeconds: 5
