apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: koo-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: koo-api
              servicePort: 80
